"""add item stat bonuses

Revision ID: 32809aec4946
Revises: 8b4b8f0124f0
Create Date: 2026-03-22 09:25:10.536899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32809aec4946'
down_revision: Union[str, Sequence[str], None] = '8b4b8f0124f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_definitions', sa.Column('stat_bonuses_json', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item_definitions', 'stat_bonuses_json')
    # ### end Alembic commands ###
