"""add quests

Revision ID: 434ba322dec1
Revises: f752fb0f5279
Create Date: 2026-03-28 22:54:46.501817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '434ba322dec1'
down_revision: Union[str, Sequence[str], None] = 'f752fb0f5279'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quest_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('objective_type', sa.String(length=50), nullable=False),
    sa.Column('target_code', sa.String(length=100), nullable=False),
    sa.Column('required_quantity', sa.Integer(), nullable=False),
    sa.Column('reward_gold', sa.Integer(), nullable=False),
    sa.Column('reward_xp', sa.Integer(), nullable=False),
    sa.Column('reward_items_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quest_definitions_code'), 'quest_definitions', ['code'], unique=True)
    op.create_table('player_quest_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('quest_definition_id', sa.Integer(), nullable=False),
    sa.Column('progress_quantity', sa.Integer(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('is_claimed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['quest_definition_id'], ['quest_definitions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'quest_definition_id', name='uq_player_quest')
    )
    op.create_index(op.f('ix_player_quest_states_player_id'), 'player_quest_states', ['player_id'], unique=False)
    op.create_index(op.f('ix_player_quest_states_quest_definition_id'), 'player_quest_states', ['quest_definition_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_player_quest_states_quest_definition_id'), table_name='player_quest_states')
    op.drop_index(op.f('ix_player_quest_states_player_id'), table_name='player_quest_states')
    op.drop_table('player_quest_states')
    op.drop_index(op.f('ix_quest_definitions_code'), table_name='quest_definitions')
    op.drop_table('quest_definitions')
    # ### end Alembic commands ###
