"""events: active_events, participations, scheduler_state, status_effects

Revision ID: 43f719faaa5d
Revises: a2c4e6f8b0d1
Create Date: 2026-08-15 20:47:36.961399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43f719faaa5d'
down_revision: Union[str, Sequence[str], None] = 'a2c4e6f8b0d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_scheduler_state',
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('last_spawn_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('event_type')
    )
    op.create_table('active_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('winner_player_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['winner_player_id'], ['players.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_active_events_event_type'), 'active_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_active_events_expires_at'), 'active_events', ['expires_at'], unique=False)
    op.create_index(op.f('ix_active_events_status'), 'active_events', ['status'], unique=False)
    op.create_table('player_status_effects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('multiplier', sa.Float(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_status_effects_expires_at'), 'player_status_effects', ['expires_at'], unique=False)
    op.create_index(op.f('ix_player_status_effects_player_id'), 'player_status_effects', ['player_id'], unique=False)
    op.create_table('event_participations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('choice', sa.String(length=40), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['active_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'player_id', name='uq_event_participation')
    )
    op.create_index(op.f('ix_event_participations_event_id'), 'event_participations', ['event_id'], unique=False)
    op.create_index(op.f('ix_event_participations_player_id'), 'event_participations', ['player_id'], unique=False)
    # NB : le bruit autogen sur `player_equipment_set_items` (drift d'index d'une
    # migration antérieure) a été retiré — hors périmètre de ce lot.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_participations_player_id'), table_name='event_participations')
    op.drop_index(op.f('ix_event_participations_event_id'), table_name='event_participations')
    op.drop_table('event_participations')
    op.drop_index(op.f('ix_player_status_effects_player_id'), table_name='player_status_effects')
    op.drop_index(op.f('ix_player_status_effects_expires_at'), table_name='player_status_effects')
    op.drop_table('player_status_effects')
    op.drop_index(op.f('ix_active_events_status'), table_name='active_events')
    op.drop_index(op.f('ix_active_events_expires_at'), table_name='active_events')
    op.drop_index(op.f('ix_active_events_event_type'), table_name='active_events')
    op.drop_table('active_events')
    op.drop_table('event_scheduler_state')
    # ### end Alembic commands ###
