"""artisans : commandes de travail + maitrise

Revision ID: 45071d7bf009
Revises: 610851b0d9d3
Create Date: 2026-08-30 21:52:57.986744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45071d7bf009'
down_revision: Union[str, Sequence[str], None] = '610851b0d9d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # (bruit d'autogenerate sur player_equipment_set_items retiré : dérive
    #  antérieure, sans rapport avec ce chantier)
    op.create_table('player_artisan_mastery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('artisan_code', sa.String(length=40), nullable=False),
    sa.Column('orders_completed', sa.Integer(), nullable=False),
    sa.Column('gold_spent', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'artisan_code', name='uq_player_artisan')
    )
    op.create_index(op.f('ix_player_artisan_mastery_artisan_code'), 'player_artisan_mastery', ['artisan_code'], unique=False)
    op.create_index(op.f('ix_player_artisan_mastery_player_id'), 'player_artisan_mastery', ['player_id'], unique=False)
    op.create_table('player_work_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('artisan_code', sa.String(length=40), nullable=False),
    sa.Column('recipe_code', sa.String(length=100), nullable=False),
    sa.Column('result_item_definition_id', sa.Integer(), nullable=False),
    sa.Column('result_quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('gold_paid', sa.Integer(), nullable=False),
    sa.Column('item_power', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ready_at', sa.DateTime(), nullable=False),
    sa.Column('collected_at', sa.DateTime(), nullable=True),
    sa.Column('notify_channel_id', sa.Integer(), nullable=False),
    sa.Column('notified', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['result_item_definition_id'], ['item_definitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_work_orders_artisan_code'), 'player_work_orders', ['artisan_code'], unique=False)
    op.create_index(op.f('ix_player_work_orders_player_id'), 'player_work_orders', ['player_id'], unique=False)
    op.create_index(op.f('ix_player_work_orders_status'), 'player_work_orders', ['status'], unique=False)
    op.create_index('ix_work_order_ready_at', 'player_work_orders', ['status', 'ready_at'], unique=False)
    op.create_index('uq_player_active_work_order', 'player_work_orders', ['player_id', 'artisan_code'], unique=True, sqlite_where=sa.text("status IN ('in_progress', 'ready')"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_player_active_work_order', table_name='player_work_orders', sqlite_where=sa.text("status IN ('in_progress', 'ready')"))
    op.drop_index('ix_work_order_ready_at', table_name='player_work_orders')
    op.drop_index(op.f('ix_player_work_orders_status'), table_name='player_work_orders')
    op.drop_index(op.f('ix_player_work_orders_player_id'), table_name='player_work_orders')
    op.drop_index(op.f('ix_player_work_orders_artisan_code'), table_name='player_work_orders')
    op.drop_table('player_work_orders')
    op.drop_index(op.f('ix_player_artisan_mastery_player_id'), table_name='player_artisan_mastery')
    op.drop_index(op.f('ix_player_artisan_mastery_artisan_code'), table_name='player_artisan_mastery')
    op.drop_table('player_artisan_mastery')
    # ### end Alembic commands ###
