"""admin_commands: pont admin web to bot

Revision ID: 610851b0d9d3
Revises: ef9469310c5d
Create Date: 2026-08-16 13:38:59.154973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '610851b0d9d3'
down_revision: Union[str, Sequence[str], None] = 'ef9469310c5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_commands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('result', sa.Text(), nullable=False),
    sa.Column('requested_by', sa.BigInteger(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_commands_action'), 'admin_commands', ['action'], unique=False)
    op.create_index(op.f('ix_admin_commands_created_at'), 'admin_commands', ['created_at'], unique=False)
    op.create_index(op.f('ix_admin_commands_status'), 'admin_commands', ['status'], unique=False)
    op.drop_index(op.f('ix_player_equipment_set_items_set_id'), table_name='player_equipment_set_items')
    op.create_index(op.f('ix_player_equipment_set_items_item_definition_id'), 'player_equipment_set_items', ['item_definition_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_player_equipment_set_items_equipment_set_id'), table_name='player_equipment_set_items')
    op.create_index(op.f('ix_player_equipment_set_items_item_id'), 'player_equipment_set_items', ['item_definition_id'], unique=False)
    op.drop_index(op.f('ix_admin_commands_status'), table_name='admin_commands')
    op.drop_index(op.f('ix_admin_commands_created_at'), table_name='admin_commands')
    op.drop_index(op.f('ix_admin_commands_action'), table_name='admin_commands')
    op.drop_table('admin_commands')
    # ### end Alembic commands ###
