"""add crafts

Revision ID: 7d119c0b61a1
Revises: a06284c36f8e
Create Date: 2026-03-28 21:56:26.025252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d119c0b61a1'
down_revision: Union[str, Sequence[str], None] = 'a06284c36f8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('craft_recipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('result_item_definition_id', sa.Integer(), nullable=False),
    sa.Column('result_quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['result_item_definition_id'], ['item_definitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_craft_recipes_code'), 'craft_recipes', ['code'], unique=True)
    op.create_index(op.f('ix_craft_recipes_result_item_definition_id'), 'craft_recipes', ['result_item_definition_id'], unique=False)
    op.create_table('craft_recipe_ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('craft_recipe_id', sa.Integer(), nullable=False),
    sa.Column('item_definition_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['craft_recipe_id'], ['craft_recipes.id'], ),
    sa.ForeignKeyConstraint(['item_definition_id'], ['item_definitions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('craft_recipe_id', 'item_definition_id', name='uq_craft_ingredient')
    )
    op.create_index(op.f('ix_craft_recipe_ingredients_craft_recipe_id'), 'craft_recipe_ingredients', ['craft_recipe_id'], unique=False)
    op.create_index(op.f('ix_craft_recipe_ingredients_item_definition_id'), 'craft_recipe_ingredients', ['item_definition_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_craft_recipe_ingredients_item_definition_id'), table_name='craft_recipe_ingredients')
    op.drop_index(op.f('ix_craft_recipe_ingredients_craft_recipe_id'), table_name='craft_recipe_ingredients')
    op.drop_table('craft_recipe_ingredients')
    op.drop_index(op.f('ix_craft_recipes_result_item_definition_id'), table_name='craft_recipes')
    op.drop_index(op.f('ix_craft_recipes_code'), table_name='craft_recipes')
    op.drop_table('craft_recipes')
    # ### end Alembic commands ###
