"""add class unlock requirements

Revision ID: 881b577f4f75
Revises: d98ad92d7d7a
Create Date: 2026-03-29 14:19:57.695465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '881b577f4f75'
down_revision: Union[str, Sequence[str], None] = 'd98ad92d7d7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('class_definitions', sa.Column('unlock_requirements_json', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('class_definitions', 'unlock_requirements_json')
    # ### end Alembic commands ###
