"""add player equipment

Revision ID: 8b4b8f0124f0
Revises: f7f457bdb71a
Create Date: 2026-03-21 22:53:46.768995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b4b8f0124f0'
down_revision: Union[str, Sequence[str], None] = 'f7f457bdb71a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('slot', sa.String(length=50), nullable=False),
    sa.Column('item_definition_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['item_definition_id'], ['item_definitions.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'slot', name='uq_player_equipment_slot')
    )
    op.create_index(op.f('ix_player_equipment_item_definition_id'), 'player_equipment', ['item_definition_id'], unique=False)
    op.create_index(op.f('ix_player_equipment_player_id'), 'player_equipment', ['player_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_player_equipment_player_id'), table_name='player_equipment')
    op.drop_index(op.f('ix_player_equipment_item_definition_id'), table_name='player_equipment')
    op.drop_table('player_equipment')
    # ### end Alembic commands ###
