"""add mob image url

Revision ID: 945fdf0593da
Revises: 552d5a97e9a0
Create Date: 2026-03-31 22:44:08.041454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '945fdf0593da'
down_revision: Union[str, Sequence[str], None] = '552d5a97e9a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mob_definitions', sa.Column('image_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mob_definitions', 'image_url')
    # ### end Alembic commands ###
