"""add current_hp to mobs

Revision ID: aa3213f3173b
Revises: f6e308545883
Create Date: 2026-04-12 00:18:13.754835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa3213f3173b'
down_revision: Union[str, Sequence[str], None] = 'f6e308545883'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mob_definitions', sa.Column('image_name', sa.String(length=100), nullable=True))
    op.add_column('mob_definitions', sa.Column('current_hp', sa.Integer(), nullable=False))
    op.drop_column('mob_definitions', 'image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mob_definitions', sa.Column('image_url', sa.VARCHAR(length=500), nullable=True))
    op.drop_column('mob_definitions', 'current_hp')
    op.drop_column('mob_definitions', 'image_name')
    # ### end Alembic commands ###
