"""forge: player_item_levels

Revision ID: ef9469310c5d
Revises: 43f719faaa5d
Create Date: 2026-08-15 21:34:17.125109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef9469310c5d'
down_revision: Union[str, Sequence[str], None] = '43f719faaa5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_item_levels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('item_definition_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['item_definition_id'], ['item_definitions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'item_definition_id', name='uq_player_item_level')
    )
    op.create_index(op.f('ix_player_item_levels_item_definition_id'), 'player_item_levels', ['item_definition_id'], unique=False)
    op.create_index(op.f('ix_player_item_levels_player_id'), 'player_item_levels', ['player_id'], unique=False)
    # (bruit autogen sur player_equipment_set_items retiré — hors périmètre)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_player_item_levels_player_id'), table_name='player_item_levels')
    op.drop_index(op.f('ix_player_item_levels_item_definition_id'), table_name='player_item_levels')
    op.drop_table('player_item_levels')
    # ### end Alembic commands ###
