"""add spawn_weight to mob

Revision ID: f6e308545883
Revises: 4f90a26b07f5
Create Date: 2026-04-06 23:11:17.900065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6e308545883'
down_revision: Union[str, Sequence[str], None] = '4f90a26b07f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mob_definitions', sa.Column('spawn_weight', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mob_definitions', 'spawn_weight')
    # ### end Alembic commands ###
