"""add player cooldowns

Revision ID: f752fb0f5279
Revises: 7d119c0b61a1
Create Date: 2026-03-28 22:04:48.870106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f752fb0f5279'
down_revision: Union[str, Sequence[str], None] = '7d119c0b61a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_cooldowns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('action_key', sa.String(length=100), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('next_available_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'action_key', name='uq_player_cooldown_action')
    )
    op.create_index(op.f('ix_player_cooldowns_action_key'), 'player_cooldowns', ['action_key'], unique=False)
    op.create_index(op.f('ix_player_cooldowns_player_id'), 'player_cooldowns', ['player_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_player_cooldowns_player_id'), table_name='player_cooldowns')
    op.drop_index(op.f('ix_player_cooldowns_action_key'), table_name='player_cooldowns')
    op.drop_table('player_cooldowns')
    # ### end Alembic commands ###
