"""add inventory and item definitions

Revision ID: f7f457bdb71a
Revises: 83994272ea1b
Create Date: 2026-03-21 22:43:46.407891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7f457bdb71a'
down_revision: Union[str, Sequence[str], None] = '83994272ea1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('rarity', sa.String(length=50), nullable=False),
    sa.Column('stackable', sa.Boolean(), nullable=False),
    sa.Column('max_stack', sa.Integer(), nullable=True),
    sa.Column('sell_price', sa.Integer(), nullable=False),
    sa.Column('buy_price', sa.Integer(), nullable=True),
    sa.Column('icon', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_definitions_code'), 'item_definitions', ['code'], unique=True)
    op.create_table('player_inventory_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('item_definition_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['item_definition_id'], ['item_definitions.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'item_definition_id', name='uq_player_item')
    )
    op.create_index(op.f('ix_player_inventory_items_item_definition_id'), 'player_inventory_items', ['item_definition_id'], unique=False)
    op.create_index(op.f('ix_player_inventory_items_player_id'), 'player_inventory_items', ['player_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_player_inventory_items_player_id'), table_name='player_inventory_items')
    op.drop_index(op.f('ix_player_inventory_items_item_definition_id'), table_name='player_inventory_items')
    op.drop_table('player_inventory_items')
    op.drop_index(op.f('ix_item_definitions_code'), table_name='item_definitions')
    op.drop_table('item_definitions')
    # ### end Alembic commands ###
