"""add mob loot table

Revision ID: ffcc4d42e55f
Revises: dbe1e648a426
Create Date: 2026-03-22 10:12:12.069033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffcc4d42e55f'
down_revision: Union[str, Sequence[str], None] = 'dbe1e648a426'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mob_definitions', sa.Column('loot_table_json', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mob_definitions', 'loot_table_json')
    # ### end Alembic commands ###
